apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
    prometheus.io/scrape: "true"
spec:
  selector:
    app: backend
  ports:
  - name: http 
    port: 3001
    targetPort: 3001