apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
    prometheus: monitor
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 5500
      protocol: TCP
      name: http
  type: NodePort
