apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  labels:
    release: monitor
spec:
  selector:
    matchLabels:
      prometheus: monitor
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /
      interval: 15s
