version: '3'
services:
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "8080:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - graphite_data:/opt/graphite/storage

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - graphite

volumes:
  graphite_data:
  grafana_data: